### ISSUE TITLE
Couple of recipe adjustments

### ISSUE THREAD

**Issue by anoomolu** [ApolloDatapacks/mortar#2]
Hiya! Absolutely love the textures, especially all the chiselled bricks!

I noticed a couple of recipes that you may want to tweak/add, listed below.

Crafting table:
- Quartz Walls being made from Quartz instead of Quartz Blocks

Stonecutter:
- Mossy Stone Bricks -> Chiseled
- Prismarine and Prismarine Bricks -> Chiseled instead of just latter
- Quartz Block -> Wall
- Quartz Block and Quartz Bricks -> Quartz Brick Slab/Stair/Wall instead of just latter
- End Stone and End Stone bricks -> Chiselled instead of just latter 
- Normal and Cut/Polished variants -> Cut/Polished walls/slabs/stairs instead of just the latter (Applies to Andesite, Calcite, Diorite, Granite, Red Sandstone, Sandstone, Tuff)

I can upload the recipes I've made for each to google drive or something if it's less hassle for you (although there may be duplicate recipes where two blocks can be inputs). Thanks for the lovely mod :)

**Comment by Apollounknowndev** [comment]
There's an update currently in development which adds most of these recipes. I'll add crafting quartz variants from quartz directly to that update, thank you for the suggestion!
