### ISSUE TITLE
Calcite Brick Wall Not Connecting

### ISSUE THREAD

**Issue by draklorx** [ApolloDatapacks/mortar#3]
When you place a calcite brick wall next to another wall of any other type, the calcite brick wall tries to connect, but the other wall type does not.

When you place a calcite brick wall next to another calcite brick wall it doesn't neither one tries to connect and you get a bunch of calcite brick pillars.

NOTE: This was tried with a bunch of other mods, and not strictly this one, so it could be a wacky mod interaction. This may effect other walls, but I went through about half of them and they all seemed to work fine besides the calcite brick wall.

**Comment by Apollounknowndev** [comment]
Fixed in v2.0.3.
